version: "3.8"

services:
  grafana:
      image: grafana/grafana-enterprise
      container_name: grafana-server
      restart: always
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_INSTALL_PLUGINS=grafana-mqtt-datasource
        - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-mqtt-datasource
      ports:
        - 3000:3000
      volumes:
        - ./grafana-plugins:/var/lib/grafana/plugins
        - grafana_data:/var/lib/grafana    
      
volumes:
  grafana_data: {}
  
networks:
  grafana_network: