services:
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.4.4
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - 22181:2181
  
  # kafka:
  #   image: confluentinc/cp-kafka:7.4.4
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - 29092:29092
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
  # kafka-mqtt-bridge:
  #   image: kafka-mqtt-bridge:latest
  #   links:
  #       - "kafka:kafka"
  #   depends_on:
  #       - kafka

  influxdb: 
    image: influxdb:latest 
    ports:
      - 8086:8086 
    volumes:
      - ./influxdb/influxdb-data:/var/lib/influxdb2
      - ./influxdb/influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=cliente
      - DOCKER_INFLUXDB_INIT_PASSWORD=testuma1
      - DOCKER_INFLUXDB_INIT_ORG=uma
      - DOCKER_INFLUXDB_INIT_BUCKET=esp32_db
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=2XrNzUjeVQtF-ktny3L4fUKNKTzc7mBMb9Wi17hkOcgEYQNCF3mBUDRmmgRPqCpQr7XnXOui79PksIGN37Jg7w==

  telegraf: 
    image: telegraf:latest
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf 
    depends_on: 
      - influxdb
  
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=grafana-mqtt-datasource
    volumes:
      - ./grafana/grafana-provisioning:/etc/grafana/provisioning
      - ./grafana/grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
      - telegraf

        
#  sudo docker compose -f docker-compose.yml up --pull always