version: "1.0" 
services:
    
    zookeeper:
        image: bitnami/zookeeper
        container_name: zookeeper
        ports:
        - '2181:2181'
        environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
        - kafka

    kafka1:
        #using the version 3.3.1 is because of an strange bug in one of the latest versions of kafka that comes from a hardware or OS incompatibility. you can try sometimes later with newest version to be sure that if there is no problem then back to the latest version.
        image: bitnami/kafka:latest
        container_name: kafka1
        ports:
        - '9093:9093'
        - '9092:9092'
        environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
        - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://localhost:9093,
        - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
        - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
        depends_on:
        - zookeeper
        networks:
        - kafka
        - grafana

    kafdrop:
        image: obsidiandynamics/kafdrop:latest
        container_name: kafdrop
        ports:
        - 9000:9000
        environment:
        - KAFKA_BROKERCONNECT=kafka1:9092
        depends_on:
        - kafka1
        networks:
        - kafka
    
    telegraf:
        image: telegraf:latest
        container_name: telegraf
        depends_on:
            - zookeeper
            - kafka1
        restart: unless-stopped
        networks:
          - kafka
        volumes:
            - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    
    grafana:
        image: grafana/grafana  
        container_name: grafana
        environment:
            - GF_SECURITY_ADMIN_USERNAME=admin
            - GF_SECURITY_ADMIN_PASSWORD=1234
        ports:
            - "3000:3000"
        #  volumes: 
        #      - ./grafana/data:/var/lib/grafana
        networks:
            - grafana
            - line
        depends_on:
            - telegraf

    # temperature-producer:
    #     build:
    #       context: ./DataSender
    #       dockerfile: dockerfile
    #     container_name: temperature-producer
    #     depends_on:
    #       - kafka1
    #     networks:
    #       - kafka
         
    ### NETWORKS
networks:
    kafka: # connection to kafka
        name: kafka
        driver: bridge
    line: # connection to linesender
        name: line
        driver: bridge
    grafana:
        name: grafana
        driver: bridge
        
#  sudo docker compose -f docker-compose.yml up --pull always