services:
  influxdb: 
    image: influxdb:latest 
    ports:
      - 8086:8086 
    volumes:
      - ./influxdb/influxdb-data:/var/lib/influxdb2
      - ./influxdb/influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=cliente
      - DOCKER_INFLUXDB_INIT_PASSWORD=testuma1
      - DOCKER_INFLUXDB_INIT_ORG=uma
      - DOCKER_INFLUXDB_INIT_BUCKET=esp32_db

  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf 
    depends_on: 
      - influxdb
  
  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/grafana-provisioning:/etc/grafana/provisioning
      - ./grafana/grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
      - telegraf